In [1]:
import os
import random
import time
import numpy as np
import pandas as pd
from tqdm import tqdm
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.models as models
import torch.multiprocessing
torch.multiprocessing.set_start_method('spawn', force=True)

from torchvision import  models,transforms
from torchvision.models import mobilenet_v3_large, MobileNet_V3_Large_Weights

from sklearn.metrics import (accuracy_score, precision_recall_fscore_support, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix)

In [2]:
class ConcreteCrackDataset(Dataset):
  
    def __init__(self, csv_file, root_dir, transform=None):
        self.annotations = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform
        self.label_map = {"Non-cracked": 0, "Cracked": 1}
    
    def __len__(self):
        return len(self.annotations)
    
    def __getitem__(self, idx):
        img_name = os.path.join(self.root_dir, self.annotations.iloc[idx, 0])
        image = Image.open(img_name).convert("RGB")
        label_str = self.annotations.iloc[idx, 1]
        
        # Handle case sensitivity and strip any whitespace
        label_str = label_str.strip()
        if label_str.lower() == "non-cracked" or label_str.lower() == "non-crack" or label_str.lower() == "non-cracked":
            label = 0
        elif label_str.lower() == "cracked" or label_str.lower() == "crack":
            label = 1
        else:
            print(f"Unknown label: {label_str}, defaulting to Non-cracked (0)")
            label = 0
        
        if self.transform:
            image = self.transform(image)
        
        return image, label


In [3]:
# Load pretrained MobileNetV3 model
def get_MobileNetV3_model(num_classes=2):

    weights = MobileNet_V3_Large_Weights.DEFAULT
    model = mobilenet_v3_large(weights=weights)
    model.classifier[3] = nn.Linear(model.classifier[3].in_features, num_classes)
    
    return model

In [4]:
def evaluate(model, data_loader, device):
    model.eval()
    correct = 0
    total = 0
    all_preds = []
    all_targets = []
    
    with torch.no_grad():
        for images, targets in tqdm(data_loader, desc="Evaluating"):
            images = images.to(device)
            targets = targets.to(device)
            
            # Get predictions
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            
            # Update statistics
            total += targets.size(0)
            correct += (predicted == targets).sum().item()
            
            # Store predictions and targets for additional metrics
            all_preds.extend(predicted.cpu().numpy())
            all_targets.extend(targets.cpu().numpy())
    
    # Calculate accuracy
    accuracy = 100 * correct / total
    
    # Calculate confusion matrix
    cm = confusion_matrix(all_targets, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(all_targets, all_preds, average='binary')
    
    print(f"Accuracy: {accuracy:.2f}%")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"Confusion Matrix:\n{cm}")
    
    return {
        "accuracy": torch.tensor(accuracy),
        "precision": torch.tensor(precision),
        "recall": torch.tensor(recall),
        "f1": torch.tensor(f1)
    }

In [5]:
def train_one_epoch(model, data_loader, criterion, optimizer, device):
    model.train()
    
    total_loss = 0
    num_batches = 0
    correct = 0
    total = 0
    
    for images, targets in tqdm(data_loader, desc="Training"):
        try:
            # Move data to device
            images = images.to(device)
            targets = targets.to(device)
            
            # Zero the parameter gradients
            optimizer.zero_grad()
            
            # Forward pass
            outputs = model(images)
            loss = criterion(outputs, targets)
            
            # Backward pass
            loss.backward()
            
            # Clip gradients to prevent explosion
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            
            # Update weights
            optimizer.step()
            
            # Update statistics
            total_loss += loss.item()
            num_batches += 1
            
            # Calculate accuracy
            _, predicted = torch.max(outputs.data, 1)
            total += targets.size(0)
            correct += (predicted == targets).sum().item()
            
            # Print loss occasionally
            if num_batches % 50 == 0:
                accuracy = 100 * correct / total
                print(f"Batch {num_batches}, Loss: {loss.item():.4f}, Accuracy: {accuracy:.2f}%")
                
        except Exception as e:
            print(f"Error in batch: {e}")
            continue
    
    # Calculate average loss and accuracy
    if num_batches == 0:
        print("WARNING: No valid batches in this epoch!")
        return 0.0, 0.0
    
    avg_loss = total_loss / num_batches
    accuracy = 100 * correct / total
    
    print(f"Processed {num_batches} batches")
    print(f"Training Loss: {avg_loss:.4f}, Accuracy: {accuracy:.2f}%")
    
    return avg_loss, accuracy

In [6]:
# Function to train the model
def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler, device, num_epochs):
    best_accuracy = 0.0
    best_model_wts = None
    
    for epoch in range(num_epochs):
        print(f"Epoch {epoch+1}/{num_epochs}")
        print("-" * 10)
        
        # Train for one epoch
        epoch_loss, train_accuracy = train_one_epoch(model, train_loader, criterion, optimizer, device)
        print(f"Training Loss: {epoch_loss:.4f}, Training Accuracy: {train_accuracy:.2f}%")
        
        # Update learning rate
        scheduler.step()
        
        # Evaluate on validation set
        val_metrics = evaluate(model, val_loader, device)
        val_accuracy = val_metrics['accuracy'].item()
        val_f1 = val_metrics['f1'].item()
        
        print(f"Validation Accuracy: {val_accuracy:.2f}%, F1-Score: {val_f1:.4f}")
        
        # Save best model based on accuracy
        if val_accuracy > best_accuracy:
            best_accuracy = val_accuracy
            best_model_wts = model.state_dict().copy()
            torch.save(best_model_wts, f'best_model_epoch_{epoch+1}.pth')
            print(f"Saved best model with Accuracy: {best_accuracy:.2f}%")
        
        print()
    
    # Load best model weights
    model.load_state_dict(best_model_wts)
    return model, best_accuracy


In [8]:
def main():
    
    # Set random seeds for reproducibility
    random.seed(42)
    np.random.seed(42)
    torch.manual_seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(42)
    
    # Set device
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    print(f"Using device: {device}")
    
    # Transforms
    transform = transforms.Compose([
        transforms.Resize((224, 224)),  # MobileNetV3 typically uses 224x224
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    train_dataset = ConcreteCrackDataset('../artifact_folder/train6040/labels.csv', '../artifact_folder/train6040/images', transform)
    val_dataset = ConcreteCrackDataset('../artifact_folder/val/labels.csv', '../artifact_folder/val/images', transform)
    test_dataset = ConcreteCrackDataset('../artifact_folder/test/labels.csv', '../artifact_folder/test/images', transform)
    
    # Check if datasets are loaded correctly
    print(f"Train dataset size: {len(train_dataset)}")
    print(f"Val dataset size: {len(val_dataset)}")
    print(f"Test dataset size: {len(test_dataset)}")
    print(f"----------------------------------------------------------------------------")
    
    # Verify a few samples to ensure labels are valid
    print("Checking a few samples from training set:")
    for i in range(min(3, len(train_dataset))):
        img, label = train_dataset[i]
        print(f"Sample {i} - Image shape: {img.shape}, Label: {label}")

    # Use a batch size suitable for MobileNetV3
    batch_size = 32
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)
    test_loader = DataLoader(test_dataset, batch_size=batch_size)
    # Get MobileNetV3 model
    model = get_MobileNetV3_model(num_classes=2)  # 2 classes: Non-cracked (0) / Cracked (1)
    model.to(device)
    # Define loss function
    criterion = nn.CrossEntropyLoss()
    # Define optimizer and learning rate scheduler
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.0001)
    # Use learning rate scheduler to reduce lr by 0.1 every 3 epochs
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.1)
    print(f"----------------------------------------------------------------------------")
    # Train model
    print("Starting training...")
    start_time = time.time()
    model, best_accuracy = train_model(
        model,
        train_loader,
        val_loader,
        criterion,
        optimizer,
        scheduler,
        device,
        num_epochs=10)
    end_time = time.time()
    print(f"Training completed in {(end_time - start_time) / 60:.2f} minutes")
    print(f"Best validation accuracy: {best_accuracy:.2f}%")
    torch.save(model.state_dict(), '6040_MobileNetV3_concrete_crack_detector.pth')
    print(f"----------------------------------------------------------------------------")
    


Run Entire Processes to get MobileNetV3_concrete_crack_detector

In [9]:
if __name__ == "__main__":
    main()

Using device: cpu
Train dataset size: 21210
Val dataset size: 8413
Test dataset size: 8415
----------------------------------------------------------------------------
Checking a few samples from training set:
Sample 0 - Image shape: torch.Size([3, 224, 224]), Label: 0
Sample 1 - Image shape: torch.Size([3, 224, 224]), Label: 0
Sample 2 - Image shape: torch.Size([3, 224, 224]), Label: 0
----------------------------------------------------------------------------
Starting training...
Epoch 1/10
----------


Training:   8%|▊         | 50/663 [02:44<34:56,  3.42s/it]

Batch 50, Loss: 0.5093, Accuracy: 74.31%


Training:  15%|█▌        | 100/663 [05:26<30:43,  3.27s/it]

Batch 100, Loss: 0.2248, Accuracy: 77.84%


Training:  23%|██▎       | 150/663 [08:11<28:14,  3.30s/it]

Batch 150, Loss: 0.2449, Accuracy: 79.44%


Training:  30%|███       | 200/663 [10:52<24:49,  3.22s/it]

Batch 200, Loss: 0.4285, Accuracy: 80.19%


Training:  38%|███▊      | 250/663 [13:35<22:54,  3.33s/it]

Batch 250, Loss: 0.3276, Accuracy: 80.39%


Training:  45%|████▌     | 300/663 [16:26<20:28,  3.38s/it]

Batch 300, Loss: 0.1971, Accuracy: 81.02%


Training:  53%|█████▎    | 350/663 [19:12<16:54,  3.24s/it]

Batch 350, Loss: 0.2682, Accuracy: 81.32%


Training:  60%|██████    | 400/663 [21:55<14:23,  3.28s/it]

Batch 400, Loss: 0.3042, Accuracy: 81.78%


Training:  68%|██████▊   | 450/663 [24:37<11:29,  3.24s/it]

Batch 450, Loss: 0.2751, Accuracy: 82.01%


Training:  75%|███████▌  | 500/663 [27:20<08:44,  3.22s/it]

Batch 500, Loss: 0.3830, Accuracy: 82.00%


Training:  83%|████████▎ | 550/663 [30:04<06:19,  3.36s/it]

Batch 550, Loss: 0.2038, Accuracy: 82.20%


Training:  90%|█████████ | 600/663 [32:46<03:29,  3.32s/it]

Batch 600, Loss: 0.5296, Accuracy: 82.31%


Training:  98%|█████████▊| 650/663 [35:34<00:45,  3.47s/it]

Batch 650, Loss: 0.4117, Accuracy: 82.47%


Training: 100%|██████████| 663/663 [36:17<00:00,  3.28s/it]


Processed 663 batches
Training Loss: 0.4086, Accuracy: 82.52%
Training Loss: 0.4086, Training Accuracy: 82.52%


Evaluating: 100%|██████████| 263/263 [05:25<00:00,  1.24s/it]


Accuracy: 91.42%
Precision: 0.7151
Recall: 0.7262
F1-Score: 0.7206
Confusion Matrix:
[[6760  371]
 [ 351  931]]
Validation Accuracy: 91.42%, F1-Score: 0.7206
Saved best model with Accuracy: 91.42%

Epoch 2/10
----------


Training:   8%|▊         | 50/663 [02:44<33:47,  3.31s/it]

Batch 50, Loss: 0.3332, Accuracy: 85.88%


Training:  15%|█▌        | 100/663 [05:29<30:25,  3.24s/it]

Batch 100, Loss: 0.4648, Accuracy: 85.62%


Training:  23%|██▎       | 150/663 [08:14<27:28,  3.21s/it]

Batch 150, Loss: 0.5091, Accuracy: 86.06%


Training:  30%|███       | 200/663 [10:54<24:37,  3.19s/it]

Batch 200, Loss: 0.3393, Accuracy: 85.97%


Training:  38%|███▊      | 250/663 [13:38<22:41,  3.30s/it]

Batch 250, Loss: 0.2723, Accuracy: 85.80%


Training:  45%|████▌     | 300/663 [16:25<19:23,  3.21s/it]

Batch 300, Loss: 0.4589, Accuracy: 85.67%


Training:  53%|█████▎    | 350/663 [19:03<16:31,  3.17s/it]

Batch 350, Loss: 0.4350, Accuracy: 85.67%


Training:  60%|██████    | 400/663 [21:53<15:03,  3.44s/it]

Batch 400, Loss: 0.4221, Accuracy: 85.68%


Training:  68%|██████▊   | 450/663 [24:40<11:32,  3.25s/it]

Batch 450, Loss: 0.2919, Accuracy: 85.86%


Training:  75%|███████▌  | 500/663 [27:32<09:15,  3.41s/it]

Batch 500, Loss: 0.4944, Accuracy: 85.86%


Training:  83%|████████▎ | 550/663 [30:16<06:04,  3.23s/it]

Batch 550, Loss: 0.5000, Accuracy: 85.96%


Training:  90%|█████████ | 600/663 [32:58<03:22,  3.21s/it]

Batch 600, Loss: 0.1432, Accuracy: 86.02%


Training:  98%|█████████▊| 650/663 [35:39<00:41,  3.20s/it]

Batch 650, Loss: 0.3550, Accuracy: 86.01%


Training: 100%|██████████| 663/663 [36:21<00:00,  3.29s/it]


Processed 663 batches
Training Loss: 0.3430, Accuracy: 86.01%
Training Loss: 0.3430, Training Accuracy: 86.01%


Evaluating: 100%|██████████| 263/263 [05:18<00:00,  1.21s/it]


Accuracy: 93.89%
Precision: 0.8959
Recall: 0.6778
F1-Score: 0.7718
Confusion Matrix:
[[7030  101]
 [ 413  869]]
Validation Accuracy: 93.89%, F1-Score: 0.7718
Saved best model with Accuracy: 93.89%

Epoch 3/10
----------


Training:   8%|▊         | 50/663 [02:39<32:41,  3.20s/it]

Batch 50, Loss: 0.4423, Accuracy: 88.38%


Training:  15%|█▌        | 100/663 [05:19<29:50,  3.18s/it]

Batch 100, Loss: 0.3361, Accuracy: 88.09%


Training:  23%|██▎       | 150/663 [07:59<27:23,  3.20s/it]

Batch 150, Loss: 0.1678, Accuracy: 87.85%


Training:  30%|███       | 200/663 [10:39<24:39,  3.20s/it]

Batch 200, Loss: 0.2090, Accuracy: 87.70%


Training:  38%|███▊      | 250/663 [13:20<22:04,  3.21s/it]

Batch 250, Loss: 0.3743, Accuracy: 87.26%


Training:  45%|████▌     | 300/663 [17:19<31:50,  5.26s/it]

Batch 300, Loss: 0.3289, Accuracy: 87.19%


Training:  53%|█████▎    | 350/663 [21:41<27:08,  5.20s/it]

Batch 350, Loss: 0.2726, Accuracy: 87.13%


Training:  60%|██████    | 400/663 [26:27<24:14,  5.53s/it]

Batch 400, Loss: 0.2675, Accuracy: 87.11%


Training:  68%|██████▊   | 450/663 [29:48<11:58,  3.37s/it]

Batch 450, Loss: 0.4347, Accuracy: 87.08%


Training:  75%|███████▌  | 500/663 [32:30<08:53,  3.28s/it]

Batch 500, Loss: 0.2186, Accuracy: 87.09%


Training:  83%|████████▎ | 550/663 [35:11<06:00,  3.19s/it]

Batch 550, Loss: 0.4148, Accuracy: 87.04%


Training:  90%|█████████ | 600/663 [37:51<03:24,  3.25s/it]

Batch 600, Loss: 0.2603, Accuracy: 87.04%


Training:  98%|█████████▊| 650/663 [40:39<00:44,  3.41s/it]

Batch 650, Loss: 0.2827, Accuracy: 86.96%


Training: 100%|██████████| 663/663 [41:22<00:00,  3.74s/it]


Processed 663 batches
Training Loss: 0.3177, Accuracy: 86.95%
Training Loss: 0.3177, Training Accuracy: 86.95%


Evaluating: 100%|██████████| 263/263 [05:10<00:00,  1.18s/it]


Accuracy: 93.64%
Precision: 0.8455
Recall: 0.7129
F1-Score: 0.7736
Confusion Matrix:
[[6964  167]
 [ 368  914]]
Validation Accuracy: 93.64%, F1-Score: 0.7736

Epoch 4/10
----------


Training:   8%|▊         | 50/663 [02:46<34:31,  3.38s/it]

Batch 50, Loss: 0.2990, Accuracy: 91.44%


Training:  15%|█▌        | 100/663 [05:33<31:26,  3.35s/it]

Batch 100, Loss: 0.2422, Accuracy: 91.28%


Training:  23%|██▎       | 150/663 [08:18<27:24,  3.21s/it]

Batch 150, Loss: 0.0889, Accuracy: 91.40%


Training:  30%|███       | 200/663 [10:58<24:43,  3.20s/it]

Batch 200, Loss: 0.2202, Accuracy: 91.30%


Training:  38%|███▊      | 250/663 [13:38<22:10,  3.22s/it]

Batch 250, Loss: 0.2137, Accuracy: 91.12%


Training:  45%|████▌     | 300/663 [16:18<19:23,  3.21s/it]

Batch 300, Loss: 0.1442, Accuracy: 91.18%


Training:  53%|█████▎    | 350/663 [18:59<17:48,  3.42s/it]

Batch 350, Loss: 0.0849, Accuracy: 91.22%


Training:  60%|██████    | 400/663 [21:42<14:06,  3.22s/it]

Batch 400, Loss: 0.0918, Accuracy: 91.29%


Training:  68%|██████▊   | 450/663 [24:35<12:07,  3.42s/it]

Batch 450, Loss: 0.1360, Accuracy: 91.30%


Training:  75%|███████▌  | 500/663 [27:25<09:11,  3.38s/it]

Batch 500, Loss: 0.3175, Accuracy: 91.28%


Training:  83%|████████▎ | 550/663 [30:18<06:24,  3.40s/it]

Batch 550, Loss: 0.0556, Accuracy: 91.45%


Training:  90%|█████████ | 600/663 [33:07<03:34,  3.40s/it]

Batch 600, Loss: 0.1212, Accuracy: 91.44%


Training:  98%|█████████▊| 650/663 [35:54<00:44,  3.43s/it]

Batch 650, Loss: 0.2291, Accuracy: 91.50%


Training: 100%|██████████| 663/663 [36:37<00:00,  3.31s/it]


Processed 663 batches
Training Loss: 0.2204, Accuracy: 91.51%
Training Loss: 0.2204, Training Accuracy: 91.51%


Evaluating: 100%|██████████| 263/263 [05:34<00:00,  1.27s/it]


Accuracy: 92.87%
Precision: 0.7358
Recall: 0.8300
F1-Score: 0.7801
Confusion Matrix:
[[6749  382]
 [ 218 1064]]
Validation Accuracy: 92.87%, F1-Score: 0.7801

Epoch 5/10
----------


Training:   8%|▊         | 50/663 [02:48<32:39,  3.20s/it]

Batch 50, Loss: 0.1322, Accuracy: 93.56%


Training:  15%|█▌        | 100/663 [05:29<30:02,  3.20s/it]

Batch 100, Loss: 0.1297, Accuracy: 93.62%


Training:  23%|██▎       | 150/663 [08:20<29:54,  3.50s/it]

Batch 150, Loss: 0.0816, Accuracy: 93.67%


Training:  30%|███       | 200/663 [11:04<24:39,  3.19s/it]

Batch 200, Loss: 0.1157, Accuracy: 93.66%


Training:  38%|███▊      | 250/663 [13:45<21:56,  3.19s/it]

Batch 250, Loss: 0.1416, Accuracy: 93.69%


Training:  45%|████▌     | 300/663 [16:24<19:17,  3.19s/it]

Batch 300, Loss: 0.3351, Accuracy: 93.53%


Training:  53%|█████▎    | 350/663 [19:04<16:44,  3.21s/it]

Batch 350, Loss: 0.1447, Accuracy: 93.49%


Training:  60%|██████    | 400/663 [21:44<14:07,  3.22s/it]

Batch 400, Loss: 0.1520, Accuracy: 93.37%


Training:  68%|██████▊   | 450/663 [24:23<11:19,  3.19s/it]

Batch 450, Loss: 0.1336, Accuracy: 93.27%


Training:  75%|███████▌  | 500/663 [27:03<08:38,  3.18s/it]

Batch 500, Loss: 0.2131, Accuracy: 93.13%


Training:  83%|████████▎ | 550/663 [29:42<05:58,  3.17s/it]

Batch 550, Loss: 0.1267, Accuracy: 93.11%


Training:  90%|█████████ | 600/663 [32:24<03:21,  3.20s/it]

Batch 600, Loss: 0.0811, Accuracy: 93.16%


Training:  98%|█████████▊| 650/663 [35:05<00:41,  3.21s/it]

Batch 650, Loss: 0.0719, Accuracy: 93.18%


Training: 100%|██████████| 663/663 [35:46<00:00,  3.24s/it]


Processed 663 batches
Training Loss: 0.1811, Accuracy: 93.19%
Training Loss: 0.1811, Training Accuracy: 93.19%


Evaluating: 100%|██████████| 263/263 [05:14<00:00,  1.20s/it]


Accuracy: 93.15%
Precision: 0.7455
Recall: 0.8362
F1-Score: 0.7882
Confusion Matrix:
[[6765  366]
 [ 210 1072]]
Validation Accuracy: 93.15%, F1-Score: 0.7882

Epoch 6/10
----------


Training:   8%|▊         | 50/663 [02:39<32:37,  3.19s/it]

Batch 50, Loss: 0.1171, Accuracy: 94.94%


Training:  15%|█▌        | 100/663 [05:20<30:02,  3.20s/it]

Batch 100, Loss: 0.1146, Accuracy: 94.22%


Training:  23%|██▎       | 150/663 [08:01<28:15,  3.31s/it]

Batch 150, Loss: 0.1980, Accuracy: 94.56%


Training:  30%|███       | 200/663 [10:54<27:33,  3.57s/it]

Batch 200, Loss: 0.2021, Accuracy: 94.55%


Training:  38%|███▊      | 250/663 [13:50<23:49,  3.46s/it]

Batch 250, Loss: 0.0393, Accuracy: 94.40%


Training:  45%|████▌     | 300/663 [16:44<21:01,  3.47s/it]

Batch 300, Loss: 0.0329, Accuracy: 94.35%


Training:  53%|█████▎    | 350/663 [19:38<18:01,  3.46s/it]

Batch 350, Loss: 0.2270, Accuracy: 94.24%


Training:  60%|██████    | 400/663 [22:34<15:35,  3.56s/it]

Batch 400, Loss: 0.2219, Accuracy: 94.27%


Training:  68%|██████▊   | 450/663 [25:29<12:23,  3.49s/it]

Batch 450, Loss: 0.1012, Accuracy: 94.26%


Training:  75%|███████▌  | 500/663 [28:29<09:33,  3.52s/it]

Batch 500, Loss: 0.2025, Accuracy: 94.24%


Training:  83%|████████▎ | 550/663 [31:24<06:40,  3.54s/it]

Batch 550, Loss: 0.1596, Accuracy: 94.28%


Training:  90%|█████████ | 600/663 [34:18<03:38,  3.47s/it]

Batch 600, Loss: 0.0847, Accuracy: 94.20%


Training:  98%|█████████▊| 650/663 [37:13<00:44,  3.45s/it]

Batch 650, Loss: 0.1418, Accuracy: 94.21%


Training: 100%|██████████| 663/663 [37:57<00:00,  3.44s/it]


Processed 663 batches
Training Loss: 0.1568, Accuracy: 94.19%
Training Loss: 0.1568, Training Accuracy: 94.19%


Evaluating: 100%|██████████| 263/263 [05:42<00:00,  1.30s/it]


Accuracy: 92.63%
Precision: 0.7246
Recall: 0.8331
F1-Score: 0.7750
Confusion Matrix:
[[6725  406]
 [ 214 1068]]
Validation Accuracy: 92.63%, F1-Score: 0.7750

Epoch 7/10
----------


Training:   8%|▊         | 50/663 [02:53<36:27,  3.57s/it]

Batch 50, Loss: 0.0992, Accuracy: 96.62%


Training:  15%|█▌        | 100/663 [05:49<32:33,  3.47s/it]

Batch 100, Loss: 0.0327, Accuracy: 95.97%


Training:  23%|██▎       | 150/663 [08:43<29:32,  3.46s/it]

Batch 150, Loss: 0.0790, Accuracy: 95.90%


Training:  30%|███       | 200/663 [11:36<26:33,  3.44s/it]

Batch 200, Loss: 0.2482, Accuracy: 95.86%


Training:  38%|███▊      | 250/663 [14:28<23:26,  3.41s/it]

Batch 250, Loss: 0.0818, Accuracy: 95.78%


Training:  45%|████▌     | 300/663 [17:21<20:50,  3.45s/it]

Batch 300, Loss: 0.1018, Accuracy: 95.77%


Training:  53%|█████▎    | 350/663 [20:13<17:49,  3.42s/it]

Batch 350, Loss: 0.1171, Accuracy: 95.83%


Training:  60%|██████    | 400/663 [23:04<15:05,  3.44s/it]

Batch 400, Loss: 0.1847, Accuracy: 95.81%


Training:  68%|██████▊   | 450/663 [25:53<11:53,  3.35s/it]

Batch 450, Loss: 0.2270, Accuracy: 95.69%


Training:  75%|███████▌  | 500/663 [28:37<08:41,  3.20s/it]

Batch 500, Loss: 0.1694, Accuracy: 95.62%


Training:  83%|████████▎ | 550/663 [31:28<06:56,  3.68s/it]

Batch 550, Loss: 0.0366, Accuracy: 95.65%


Training:  90%|█████████ | 600/663 [34:10<03:21,  3.19s/it]

Batch 600, Loss: 0.1770, Accuracy: 95.61%


Training:  98%|█████████▊| 650/663 [36:53<00:46,  3.56s/it]

Batch 650, Loss: 0.0794, Accuracy: 95.62%


Training: 100%|██████████| 663/663 [37:39<00:00,  3.41s/it]


Processed 663 batches
Training Loss: 0.1246, Accuracy: 95.61%
Training Loss: 0.1246, Training Accuracy: 95.61%


Evaluating: 100%|██████████| 263/263 [05:24<00:00,  1.23s/it]


Accuracy: 91.38%
Precision: 0.6697
Recall: 0.8573
F1-Score: 0.7520
Confusion Matrix:
[[6589  542]
 [ 183 1099]]
Validation Accuracy: 91.38%, F1-Score: 0.7520

Epoch 8/10
----------


Training:   8%|▊         | 50/663 [02:39<32:39,  3.20s/it]

Batch 50, Loss: 0.3039, Accuracy: 95.25%


Training:  15%|█▌        | 100/663 [05:19<29:51,  3.18s/it]

Batch 100, Loss: 0.1844, Accuracy: 95.47%


Training:  23%|██▎       | 150/663 [07:58<27:12,  3.18s/it]

Batch 150, Loss: 0.2025, Accuracy: 95.75%


Training:  30%|███       | 200/663 [10:37<24:31,  3.18s/it]

Batch 200, Loss: 0.0950, Accuracy: 95.75%


Training:  38%|███▊      | 250/663 [13:16<21:59,  3.20s/it]

Batch 250, Loss: 0.1119, Accuracy: 95.71%


Training:  45%|████▌     | 300/663 [15:56<19:20,  3.20s/it]

Batch 300, Loss: 0.0622, Accuracy: 95.61%


Training:  53%|█████▎    | 350/663 [18:35<16:38,  3.19s/it]

Batch 350, Loss: 0.0375, Accuracy: 95.63%


Training:  60%|██████    | 400/663 [21:22<14:53,  3.40s/it]

Batch 400, Loss: 0.0668, Accuracy: 95.68%


Training:  68%|██████▊   | 450/663 [24:04<11:21,  3.20s/it]

Batch 450, Loss: 0.0791, Accuracy: 95.69%


Training:  75%|███████▌  | 500/663 [26:45<08:44,  3.22s/it]

Batch 500, Loss: 0.2441, Accuracy: 95.67%


Training:  83%|████████▎ | 550/663 [29:25<06:02,  3.21s/it]

Batch 550, Loss: 0.2928, Accuracy: 95.57%


Training:  90%|█████████ | 600/663 [32:06<03:22,  3.21s/it]

Batch 600, Loss: 0.1338, Accuracy: 95.61%


Training:  98%|█████████▊| 650/663 [34:46<00:41,  3.21s/it]

Batch 650, Loss: 0.1705, Accuracy: 95.62%


Training: 100%|██████████| 663/663 [35:27<00:00,  3.21s/it]


Processed 663 batches
Training Loss: 0.1189, Accuracy: 95.63%
Training Loss: 0.1189, Training Accuracy: 95.63%


Evaluating: 100%|██████████| 263/263 [05:11<00:00,  1.18s/it]


Accuracy: 91.48%
Precision: 0.6738
Recall: 0.8541
F1-Score: 0.7534
Confusion Matrix:
[[6601  530]
 [ 187 1095]]
Validation Accuracy: 91.48%, F1-Score: 0.7534

Epoch 9/10
----------


Training:   8%|▊         | 50/663 [02:40<32:56,  3.22s/it]

Batch 50, Loss: 0.0692, Accuracy: 95.44%


Training:  15%|█▌        | 100/663 [05:21<30:08,  3.21s/it]

Batch 100, Loss: 0.1955, Accuracy: 95.97%


Training:  23%|██▎       | 150/663 [08:02<27:36,  3.23s/it]

Batch 150, Loss: 0.1745, Accuracy: 95.96%


Training:  30%|███       | 200/663 [10:43<24:49,  3.22s/it]

Batch 200, Loss: 0.1348, Accuracy: 96.00%


Training:  38%|███▊      | 250/663 [13:38<24:09,  3.51s/it]

Batch 250, Loss: 0.1038, Accuracy: 95.97%


Training:  45%|████▌     | 300/663 [16:27<20:47,  3.44s/it]

Batch 300, Loss: 0.0884, Accuracy: 95.92%


Training:  53%|█████▎    | 350/663 [19:18<17:47,  3.41s/it]

Batch 350, Loss: 0.0574, Accuracy: 95.83%


Training:  60%|██████    | 400/663 [22:08<15:28,  3.53s/it]

Batch 400, Loss: 0.3063, Accuracy: 95.84%


Training:  68%|██████▊   | 450/663 [24:57<11:40,  3.29s/it]

Batch 450, Loss: 0.0291, Accuracy: 95.80%


Training:  75%|███████▌  | 500/663 [27:39<08:42,  3.20s/it]

Batch 500, Loss: 0.0604, Accuracy: 95.86%


Training:  83%|████████▎ | 550/663 [30:21<06:01,  3.20s/it]

Batch 550, Loss: 0.0224, Accuracy: 95.81%


Training:  90%|█████████ | 600/663 [33:05<03:23,  3.23s/it]

Batch 600, Loss: 0.0268, Accuracy: 95.78%


Training:  98%|█████████▊| 650/663 [35:46<00:41,  3.21s/it]

Batch 650, Loss: 0.0477, Accuracy: 95.79%


Training: 100%|██████████| 663/663 [36:29<00:00,  3.30s/it]


Processed 663 batches
Training Loss: 0.1155, Accuracy: 95.78%
Training Loss: 0.1155, Training Accuracy: 95.78%


Evaluating: 100%|██████████| 263/263 [05:24<00:00,  1.24s/it]


Accuracy: 91.70%
Precision: 0.6843
Recall: 0.8456
F1-Score: 0.7565
Confusion Matrix:
[[6631  500]
 [ 198 1084]]
Validation Accuracy: 91.70%, F1-Score: 0.7565

Epoch 10/10
----------


Training:   8%|▊         | 50/663 [02:47<35:33,  3.48s/it]

Batch 50, Loss: 0.2337, Accuracy: 96.94%


Training:  15%|█▌        | 100/663 [05:39<38:48,  4.14s/it]

Batch 100, Loss: 0.2645, Accuracy: 96.16%


Training:  23%|██▎       | 150/663 [08:37<28:24,  3.32s/it]

Batch 150, Loss: 0.0811, Accuracy: 96.06%


Training:  30%|███       | 200/663 [11:26<26:10,  3.39s/it]

Batch 200, Loss: 0.3099, Accuracy: 95.72%


Training:  38%|███▊      | 250/663 [14:11<22:18,  3.24s/it]

Batch 250, Loss: 0.1747, Accuracy: 95.74%


Training:  45%|████▌     | 300/663 [16:53<19:20,  3.20s/it]

Batch 300, Loss: 0.1391, Accuracy: 95.94%


Training:  53%|█████▎    | 350/663 [19:33<16:40,  3.20s/it]

Batch 350, Loss: 0.0698, Accuracy: 95.96%


Training:  60%|██████    | 400/663 [22:14<14:37,  3.34s/it]

Batch 400, Loss: 0.0660, Accuracy: 96.02%


Training:  68%|██████▊   | 450/663 [25:00<11:35,  3.26s/it]

Batch 450, Loss: 0.2757, Accuracy: 95.94%


Training:  75%|███████▌  | 500/663 [27:43<09:26,  3.48s/it]

Batch 500, Loss: 0.3485, Accuracy: 95.94%


Training:  83%|████████▎ | 550/663 [30:35<06:42,  3.56s/it]

Batch 550, Loss: 0.1058, Accuracy: 95.98%


Training:  90%|█████████ | 600/663 [33:18<03:25,  3.26s/it]

Batch 600, Loss: 0.1753, Accuracy: 95.97%


Training:  98%|█████████▊| 650/663 [36:01<00:44,  3.40s/it]

Batch 650, Loss: 0.0622, Accuracy: 95.98%


Training: 100%|██████████| 663/663 [36:47<00:00,  3.33s/it]


Processed 663 batches
Training Loss: 0.1105, Accuracy: 95.98%
Training Loss: 0.1105, Training Accuracy: 95.98%


Evaluating: 100%|██████████| 263/263 [05:24<00:00,  1.23s/it]

Accuracy: 91.38%
Precision: 0.6722
Recall: 0.8479
F1-Score: 0.7499
Confusion Matrix:
[[6601  530]
 [ 195 1087]]
Validation Accuracy: 91.38%, F1-Score: 0.7499

Training completed in 424.67 minutes
Best validation accuracy: 93.89%
----------------------------------------------------------------------------


Evaluate Model using Test Set

In [10]:
# Load the model
print("Evaluating on test set...")

# Use the updated weights parameter instead of deprecated 'pretrained'
weights = MobileNet_V3_Large_Weights.DEFAULT
model = mobilenet_v3_large(weights=weights)
model.classifier[3] = nn.Linear(model.classifier[3].in_features, 2)  # 2 classes: cracked / not cracked

# Load trained weights
model.load_state_dict(torch.load('../model/6040_MobileNetV3_concrete_crack_detector.pth'))
model.eval()

# Define the transform for test data
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Evaluation function
def evaluate_model_on_split(split_name):
    base_path = f"../artifact_folder/{split_name}"
    labels_df = pd.read_csv(os.path.join(base_path, "labels.csv"))
    images_dir = os.path.join(base_path, "images")

    y_true, y_pred, y_score = [], [], []

    for _, row in labels_df.iterrows():
        img_path = os.path.join(images_dir, row["filename"])
        image = Image.open(img_path).convert("RGB")
        input_tensor = transform(image).unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(input_tensor)
            pred = output.argmax(dim=1).item()
            prob = torch.softmax(output, dim=1)[0][1].item()

        label = 1 if row["label"].lower() == "cracked" else 0
        y_true.append(label)
        y_pred.append(pred)
        y_score.append(prob)

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1-Score": f1_score(y_true, y_pred, zero_division=0),
        "AUC-ROC": roc_auc_score(y_true, y_score),
        "Confusion Matrix": confusion_matrix(y_true, y_pred).tolist()
    }

# Run on all sets
for split in ['train', 'val', 'test']:
    print(f"📊 Evaluation for {split.upper()}")
    metrics = evaluate_model_on_split(split)
    for k, v in metrics.items():
        print(f"{k}: {v}")
    print()
print(f"----------------------------------------------------------------------------")
print("Training and evaluation completed!")

Evaluating on test set...
📊 Evaluation for TRAIN
Accuracy: 0.8718764733616219
Precision: 0.9119874640898407
Recall: 0.8231966053748232
F1-Score: 0.8653202824928757
AUC-ROC: 0.9400254432394138
Confusion Matrix: [[7810, 674], [1500, 6984]]

📊 Evaluation for VAL
Accuracy: 0.9138238440508737
Precision: 0.6722325293753865
Recall: 0.8478939157566303
F1-Score: 0.7499137633666781
AUC-ROC: 0.9575235765004854
Confusion Matrix: [[6601, 530], [195, 1087]]

📊 Evaluation for TEST
Accuracy: 0.9138443256090315
Precision: 0.6677018633540373
Recall: 0.849802371541502
F1-Score: 0.7478260869565218
AUC-ROC: 0.9569137897675447
Confusion Matrix: [[6615, 535], [190, 1075]]

----------------------------------------------------------------------------
Training and evaluation completed!
