Reduce overfiting of MobileNetV3_concrete_crack_detector

In [1]:
import os
import random
import time
import numpy as np
import pandas as pd
from tqdm import tqdm
from PIL import Image
from collections import Counter

import matplotlib.pyplot as plt
import albumentations as A
from albumentations.pytorch import ToTensorV2

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import Dataset, DataLoader, random_split, WeightedRandomSampler
import torchvision.models as models
import torch.multiprocessing
torch.multiprocessing.set_start_method('spawn', force=True)

from torchvision import  models,transforms
from torchvision.models import resnet18, ResNet18_Weights, mobilenet_v3_small, mobilenet_v3_large, MobileNet_V3_Small_Weights, MobileNet_V3_Large_Weights

from sklearn.metrics import (accuracy_score, precision_recall_fscore_support, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix)

In [2]:
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed()

In [3]:
class ConcreteCrackDataset(Dataset):
  
    def __init__(self, csv_file, root_dir, transform=None):
        self.annotations = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform
        self.label_map = {"Non-cracked": 0, "Cracked": 1}
    
    def __len__(self):
        return len(self.annotations)
    
    def __getitem__(self, idx):
        img_name = os.path.join(self.root_dir, self.annotations.iloc[idx, 0])
        image = Image.open(img_name).convert("RGB")
        label_str = self.annotations.iloc[idx, 1]
        
        # Handle case sensitivity and strip any whitespace
        label_str = label_str.strip()
        if label_str.lower() == "non-cracked" or label_str.lower() == "non-crack" or label_str.lower() == "non-cracked":
            label = 0
        elif label_str.lower() == "cracked" or label_str.lower() == "crack":
            label = 1
        else:
            print(f"Unknown label: {label_str}, defaulting to Non-cracked (0)")
            label = 0
        
        if self.transform:
            image = self.transform(image)
        
        return image, label


In [4]:
# Load pretrained MobileNetV3 model
def get_MobileNetV3_model(num_classes=2):

    weights = MobileNet_V3_Large_Weights.DEFAULT
    model = mobilenet_v3_large(weights=weights)
    model.classifier[3] = nn.Linear(model.classifier[3].in_features, num_classes)
    
    return model

In [5]:
def evaluate(model, data_loader, device):
    model.eval()
    correct = 0
    total = 0
    all_preds = []
    all_targets = []
    
    with torch.no_grad():
        for images, targets in tqdm(data_loader, desc="Evaluating"):
            images = images.to(device)
            targets = targets.to(device)
            
            # Get predictions
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            
            # Update statistics
            total += targets.size(0)
            correct += (predicted == targets).sum().item()
            
            # Store predictions and targets for additional metrics
            all_preds.extend(predicted.cpu().numpy())
            all_targets.extend(targets.cpu().numpy())
    
    # Calculate accuracy
    accuracy = 100 * correct / total
    
    # Calculate confusion matrix
    cm = confusion_matrix(all_targets, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(all_targets, all_preds, average='binary')
    
    print(f"Accuracy: {accuracy:.2f}%")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"Confusion Matrix:\n{cm}")
    
    return {
        "accuracy": torch.tensor(accuracy),
        "precision": torch.tensor(precision),
        "recall": torch.tensor(recall),
        "f1": torch.tensor(f1)
    }

In [6]:
def train_one_epoch(model, data_loader, criterion, optimizer, device):
    model.train()
    
    total_loss = 0
    num_batches = 0
    correct = 0
    total = 0
    
    for images, targets in tqdm(data_loader, desc="Training"):
        try:
            # Move data to device
            images = images.to(device)
            targets = targets.to(device)
            
            # Zero the parameter gradients
            optimizer.zero_grad()
            
            # Forward pass
            outputs = model(images)
            loss = criterion(outputs, targets)
            
            # Backward pass
            loss.backward()
            
            # Clip gradients to prevent explosion
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            
            # Update weights
            optimizer.step()
            
            # Update statistics
            total_loss += loss.item()
            num_batches += 1
            
            # Calculate accuracy
            _, predicted = torch.max(outputs.data, 1)
            total += targets.size(0)
            correct += (predicted == targets).sum().item()
            
            # Print loss occasionally
            if num_batches % 50 == 0:
                accuracy = 100 * correct / total
                print(f"Batch {num_batches}, Loss: {loss.item():.4f}, Accuracy: {accuracy:.2f}%")
                
        except Exception as e:
            print(f"Error in batch: {e}")
            continue
    
    # Calculate average loss and accuracy
    if num_batches == 0:
        print("WARNING: No valid batches in this epoch!")
        return 0.0, 0.0
    
    avg_loss = total_loss / num_batches
    accuracy = 100 * correct / total
    
    print(f"Processed {num_batches} batches")
    print(f"Training Loss: {avg_loss:.4f}, Accuracy: {accuracy:.2f}%")
    
    return avg_loss, accuracy

In [7]:
# Function to train the model
def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler, device, num_epochs):
    best_accuracy = 0.0
    best_model_wts = None
    
    for epoch in range(num_epochs):
        print(f"Epoch {epoch+1}/{num_epochs}")
        print("-" * 10)
        
        # Train for one epoch
        epoch_loss, train_accuracy = train_one_epoch(model, train_loader, criterion, optimizer, device)
        print(f"Training Loss: {epoch_loss:.4f}, Training Accuracy: {train_accuracy:.2f}%")
        
        # Update learning rate
        scheduler.step()
        
        # Evaluate on validation set
        val_metrics = evaluate(model, val_loader, device)
        val_accuracy = val_metrics['accuracy'].item()
        val_f1 = val_metrics['f1'].item()
        
        print(f"Validation Accuracy: {val_accuracy:.2f}%, F1-Score: {val_f1:.4f}")
        
        # Save best model based on accuracy
        if val_accuracy > best_accuracy:
            best_accuracy = val_accuracy
            best_model_wts = model.state_dict().copy()
            torch.save(best_model_wts, f'best_model_epoch_{epoch+1}.pth')
            print(f"Saved best model with Accuracy: {best_accuracy:.2f}%")
        
        print()
    
    # Load best model weights
    model.load_state_dict(best_model_wts)
    return model, best_accuracy


In [8]:
def main():
    
    # Set random seeds for reproducibility
    set_seed(42)
    
    # Set device
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    print(f"Using device: {device}")
    
    # Transforms
    transform = transforms.Compose([
        transforms.Resize((224, 224)),  # MobileNetV3 typically uses 224x224
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    train_dataset = ConcreteCrackDataset('../artifact_folder/train/labels.csv', '../artifact_folder/train/images', transform)
    val_dataset = ConcreteCrackDataset('../artifact_folder/val/labels.csv', '../artifact_folder/val/images', transform)
    test_dataset = ConcreteCrackDataset('../artifact_folder/test/labels.csv', '../artifact_folder/test/images', transform)
    
    # Check if datasets are loaded correctly
    print(f"Train dataset size: {len(train_dataset)}")
    print(f"Val dataset size: {len(val_dataset)}")
    print(f"Test dataset size: {len(test_dataset)}")
    print(f"----------------------------------------------------------------------------")
    
    # Verify a few samples to ensure labels are valid
    print("Checking a few samples from training set:")
    for i in range(min(3, len(train_dataset))):
        img, label = train_dataset[i]
        print(f"Sample {i} - Image shape: {img.shape}, Label: {label}")

    # Use a batch size suitable for MobileNetV3
    batch_size = 32
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)
    test_loader = DataLoader(test_dataset, batch_size=batch_size)
    # Get MobileNetV3 model
    model = get_MobileNetV3_model(num_classes=2)  # 2 classes: Non-cracked (0) / Cracked (1)
    model.to(device)
    # Define loss function
    criterion = nn.CrossEntropyLoss()
    # Define optimizer and learning rate scheduler
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.0001)
    # Use learning rate scheduler to reduce lr by 0.1 every 3 epochs
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.1)
    print(f"----------------------------------------------------------------------------")
    # Train model
    print("Starting training...")
    start_time = time.time()
    model, best_accuracy = train_model(
        model,
        train_loader,
        val_loader,
        criterion,
        optimizer,
        scheduler,
        device,
        num_epochs=10)
    end_time = time.time()
    print(f"Training completed in {(end_time - start_time) / 60:.2f} minutes")
    print(f"Best validation accuracy: {best_accuracy:.2f}%")
    torch.save(model.state_dict(), 'Optimize_MobileNetV3_concrete_crack_detector.pth')
    print(f"----------------------------------------------------------------------------")
    


Run Entire Processes to get MobileNetV3_concrete_crack_detector

In [9]:
if __name__ == "__main__":
    main()

Using device: cpu
Train dataset size: 16968
Val dataset size: 8413
Test dataset size: 8415
----------------------------------------------------------------------------
Checking a few samples from training set:
Sample 0 - Image shape: torch.Size([3, 224, 224]), Label: 0
Sample 1 - Image shape: torch.Size([3, 224, 224]), Label: 0
Sample 2 - Image shape: torch.Size([3, 224, 224]), Label: 0
----------------------------------------------------------------------------
Starting training...
Epoch 1/10
----------


Training:   9%|▉         | 50/531 [02:45<25:46,  3.22s/it]

Batch 50, Loss: 0.8710, Accuracy: 72.88%


Training:  19%|█▉        | 100/531 [05:39<23:40,  3.29s/it]

Batch 100, Loss: 0.3337, Accuracy: 76.06%


Training:  28%|██▊       | 150/531 [08:24<20:24,  3.22s/it]

Batch 150, Loss: 0.2964, Accuracy: 76.92%


Training:  38%|███▊      | 200/531 [11:08<17:46,  3.22s/it]

Batch 200, Loss: 0.5450, Accuracy: 77.84%


Training:  47%|████▋     | 250/531 [13:51<14:57,  3.19s/it]

Batch 250, Loss: 0.3985, Accuracy: 78.33%


Training:  56%|█████▋    | 300/531 [16:32<12:27,  3.24s/it]

Batch 300, Loss: 0.5417, Accuracy: 78.68%


Training:  66%|██████▌   | 350/531 [19:13<09:40,  3.21s/it]

Batch 350, Loss: 0.6813, Accuracy: 78.97%


Training:  75%|███████▌  | 400/531 [21:59<07:00,  3.21s/it]

Batch 400, Loss: 0.2417, Accuracy: 79.08%


Training:  85%|████████▍ | 450/531 [24:41<04:20,  3.21s/it]

Batch 450, Loss: 0.2500, Accuracy: 79.35%


Training:  94%|█████████▍| 500/531 [27:23<01:39,  3.22s/it]

Batch 500, Loss: 0.2950, Accuracy: 79.94%


Training: 100%|██████████| 531/531 [29:01<00:00,  3.28s/it]


Processed 531 batches
Training Loss: 0.4372, Accuracy: 80.13%
Training Loss: 0.4372, Training Accuracy: 80.13%


Evaluating: 100%|██████████| 263/263 [05:19<00:00,  1.22s/it]


Accuracy: 87.21%
Precision: 0.5444
Recall: 0.7937
F1-Score: 0.6458
Confusion Matrix:
[[6356  821]
 [ 255  981]]
Validation Accuracy: 87.21%, F1-Score: 0.6458
Saved best model with Accuracy: 87.21%

Epoch 2/10
----------


Training:   9%|▉         | 50/531 [02:41<26:13,  3.27s/it]

Batch 50, Loss: 0.3623, Accuracy: 80.81%


Training:  19%|█▉        | 100/531 [05:22<22:57,  3.20s/it]

Batch 100, Loss: 0.2573, Accuracy: 82.09%


Training:  28%|██▊       | 150/531 [08:02<20:18,  3.20s/it]

Batch 150, Loss: 0.2455, Accuracy: 82.77%


Training:  38%|███▊      | 200/531 [10:42<17:31,  3.18s/it]

Batch 200, Loss: 0.3636, Accuracy: 83.34%


Training:  47%|████▋     | 250/531 [13:21<14:54,  3.18s/it]

Batch 250, Loss: 0.3353, Accuracy: 83.59%


Training:  56%|█████▋    | 300/531 [16:00<12:17,  3.19s/it]

Batch 300, Loss: 0.2611, Accuracy: 83.38%


Training:  66%|██████▌   | 350/531 [18:40<09:35,  3.18s/it]

Batch 350, Loss: 0.2625, Accuracy: 83.75%


Training:  75%|███████▌  | 400/531 [21:21<06:59,  3.20s/it]

Batch 400, Loss: 0.4222, Accuracy: 83.84%


Training:  85%|████████▍ | 450/531 [24:03<04:23,  3.25s/it]

Batch 450, Loss: 0.3560, Accuracy: 83.79%


Training:  94%|█████████▍| 500/531 [26:46<01:42,  3.31s/it]

Batch 500, Loss: 0.1979, Accuracy: 83.86%


Training: 100%|██████████| 531/531 [28:25<00:00,  3.21s/it]


Processed 531 batches
Training Loss: 0.3729, Accuracy: 83.82%
Training Loss: 0.3729, Training Accuracy: 83.82%


Evaluating: 100%|██████████| 263/263 [05:25<00:00,  1.24s/it]


Accuracy: 81.61%
Precision: 0.4353
Recall: 0.8471
F1-Score: 0.5751
Confusion Matrix:
[[5819 1358]
 [ 189 1047]]
Validation Accuracy: 81.61%, F1-Score: 0.5751

Epoch 3/10
----------


Training:   9%|▉         | 50/531 [02:42<25:48,  3.22s/it]

Batch 50, Loss: 0.2335, Accuracy: 88.06%


Training:  19%|█▉        | 100/531 [05:23<22:59,  3.20s/it]

Batch 100, Loss: 0.2656, Accuracy: 86.84%


Training:  28%|██▊       | 150/531 [08:04<20:56,  3.30s/it]

Batch 150, Loss: 0.3001, Accuracy: 86.58%


Training:  38%|███▊      | 200/531 [10:47<17:44,  3.22s/it]

Batch 200, Loss: 0.3238, Accuracy: 86.62%


Training:  47%|████▋     | 250/531 [13:28<15:01,  3.21s/it]

Batch 250, Loss: 0.4535, Accuracy: 86.51%


Training:  56%|█████▋    | 300/531 [16:10<12:20,  3.21s/it]

Batch 300, Loss: 0.3007, Accuracy: 86.45%


Training:  66%|██████▌   | 350/531 [18:53<09:45,  3.23s/it]

Batch 350, Loss: 0.4110, Accuracy: 86.47%


Training:  75%|███████▌  | 400/531 [21:40<07:30,  3.44s/it]

Batch 400, Loss: 0.3731, Accuracy: 86.18%


Training:  85%|████████▍ | 450/531 [25:15<06:05,  4.51s/it]

Batch 450, Loss: 0.2284, Accuracy: 86.27%


Training:  94%|█████████▍| 500/531 [28:58<02:16,  4.40s/it]

Batch 500, Loss: 0.1199, Accuracy: 86.09%


Training: 100%|██████████| 531/531 [31:12<00:00,  3.53s/it]


Processed 531 batches
Training Loss: 0.3321, Accuracy: 86.01%
Training Loss: 0.3321, Training Accuracy: 86.01%


Evaluating: 100%|██████████| 263/263 [06:08<00:00,  1.40s/it]


Accuracy: 93.91%
Precision: 0.8851
Recall: 0.6731
F1-Score: 0.7647
Confusion Matrix:
[[7069  108]
 [ 404  832]]
Validation Accuracy: 93.91%, F1-Score: 0.7647
Saved best model with Accuracy: 93.91%

Epoch 4/10
----------


Training:   9%|▉         | 50/531 [03:41<35:23,  4.42s/it]

Batch 50, Loss: 0.3980, Accuracy: 88.25%


Training:  19%|█▉        | 100/531 [07:23<31:49,  4.43s/it]

Batch 100, Loss: 0.1772, Accuracy: 89.41%


Training:  28%|██▊       | 150/531 [11:08<34:49,  5.48s/it]

Batch 150, Loss: 0.2088, Accuracy: 90.23%


Training:  38%|███▊      | 200/531 [15:01<26:33,  4.81s/it]

Batch 200, Loss: 0.2649, Accuracy: 90.44%


Training:  47%|████▋     | 250/531 [17:46<15:05,  3.22s/it]

Batch 250, Loss: 0.2553, Accuracy: 90.51%


Training:  56%|█████▋    | 300/531 [20:27<12:16,  3.19s/it]

Batch 300, Loss: 0.1339, Accuracy: 90.68%


Training:  66%|██████▌   | 350/531 [23:07<09:40,  3.20s/it]

Batch 350, Loss: 0.3871, Accuracy: 90.78%


Training:  75%|███████▌  | 400/531 [25:48<07:04,  3.24s/it]

Batch 400, Loss: 0.2033, Accuracy: 90.94%


Training:  85%|████████▍ | 450/531 [28:28<04:24,  3.27s/it]

Batch 450, Loss: 0.2303, Accuracy: 91.01%


Training:  94%|█████████▍| 500/531 [31:22<01:49,  3.53s/it]

Batch 500, Loss: 0.3152, Accuracy: 90.92%


Training: 100%|██████████| 531/531 [33:08<00:00,  3.74s/it]


Processed 531 batches
Training Loss: 0.2267, Accuracy: 91.04%
Training Loss: 0.2267, Training Accuracy: 91.04%


Evaluating: 100%|██████████| 263/263 [05:45<00:00,  1.31s/it]


Accuracy: 89.86%
Precision: 0.6102
Recall: 0.8576
F1-Score: 0.7131
Confusion Matrix:
[[6500  677]
 [ 176 1060]]
Validation Accuracy: 89.86%, F1-Score: 0.7131

Epoch 5/10
----------


Training:   9%|▉         | 50/531 [02:55<28:09,  3.51s/it]

Batch 50, Loss: 0.2527, Accuracy: 93.19%


Training:  19%|█▉        | 100/531 [05:48<24:37,  3.43s/it]

Batch 100, Loss: 0.3280, Accuracy: 92.78%


Training:  28%|██▊       | 150/531 [08:40<21:47,  3.43s/it]

Batch 150, Loss: 0.2085, Accuracy: 92.62%


Training:  38%|███▊      | 200/531 [11:32<18:58,  3.44s/it]

Batch 200, Loss: 0.0706, Accuracy: 92.78%


Training:  47%|████▋     | 250/531 [14:24<16:18,  3.48s/it]

Batch 250, Loss: 0.1007, Accuracy: 92.70%


Training:  56%|█████▋    | 300/531 [17:18<13:24,  3.48s/it]

Batch 300, Loss: 0.0867, Accuracy: 92.81%


Training:  66%|██████▌   | 350/531 [20:05<09:41,  3.21s/it]

Batch 350, Loss: 0.1525, Accuracy: 92.95%


Training:  75%|███████▌  | 400/531 [22:50<07:00,  3.21s/it]

Batch 400, Loss: 0.1476, Accuracy: 92.98%


Training:  85%|████████▍ | 450/531 [25:34<04:49,  3.57s/it]

Batch 450, Loss: 0.2859, Accuracy: 92.94%


Training:  94%|█████████▍| 500/531 [28:18<01:40,  3.24s/it]

Batch 500, Loss: 0.1220, Accuracy: 92.96%


Training: 100%|██████████| 531/531 [29:55<00:00,  3.38s/it]


Processed 531 batches
Training Loss: 0.1845, Accuracy: 93.02%
Training Loss: 0.1845, Training Accuracy: 93.02%


Evaluating: 100%|██████████| 263/263 [05:18<00:00,  1.21s/it]


Accuracy: 92.32%
Precision: 0.7046
Recall: 0.8220
F1-Score: 0.7588
Confusion Matrix:
[[6751  426]
 [ 220 1016]]
Validation Accuracy: 92.32%, F1-Score: 0.7588

Epoch 6/10
----------


Training:   9%|▉         | 50/531 [02:45<25:45,  3.21s/it]

Batch 50, Loss: 0.0632, Accuracy: 93.88%


Training:  19%|█▉        | 100/531 [05:30<23:21,  3.25s/it]

Batch 100, Loss: 0.1528, Accuracy: 94.31%


Training:  28%|██▊       | 150/531 [08:11<20:24,  3.21s/it]

Batch 150, Loss: 0.2871, Accuracy: 94.25%


Training:  38%|███▊      | 200/531 [10:53<17:48,  3.23s/it]

Batch 200, Loss: 0.0420, Accuracy: 94.28%


Training:  47%|████▋     | 250/531 [13:34<15:11,  3.24s/it]

Batch 250, Loss: 0.0586, Accuracy: 94.25%


Training:  56%|█████▋    | 300/531 [16:17<12:20,  3.21s/it]

Batch 300, Loss: 0.1919, Accuracy: 94.25%


Training:  66%|██████▌   | 350/531 [18:59<09:41,  3.22s/it]

Batch 350, Loss: 0.1677, Accuracy: 94.34%


Training:  75%|███████▌  | 400/531 [21:47<07:22,  3.38s/it]

Batch 400, Loss: 0.3949, Accuracy: 94.25%


Training:  85%|████████▍ | 450/531 [24:33<04:20,  3.22s/it]

Batch 450, Loss: 0.1798, Accuracy: 94.27%


Training:  94%|█████████▍| 500/531 [27:16<01:40,  3.24s/it]

Batch 500, Loss: 0.0836, Accuracy: 94.17%


Training: 100%|██████████| 531/531 [28:55<00:00,  3.27s/it]


Processed 531 batches
Training Loss: 0.1606, Accuracy: 94.12%
Training Loss: 0.1606, Training Accuracy: 94.12%


Evaluating: 100%|██████████| 263/263 [05:18<00:00,  1.21s/it]


Accuracy: 90.37%
Precision: 0.6274
Recall: 0.8487
F1-Score: 0.7215
Confusion Matrix:
[[6554  623]
 [ 187 1049]]
Validation Accuracy: 90.37%, F1-Score: 0.7215

Epoch 7/10
----------


Training:   9%|▉         | 50/531 [02:42<26:33,  3.31s/it]

Batch 50, Loss: 0.1243, Accuracy: 95.06%


Training:  19%|█▉        | 100/531 [05:24<23:28,  3.27s/it]

Batch 100, Loss: 0.3724, Accuracy: 95.12%


Training:  28%|██▊       | 150/531 [08:05<20:26,  3.22s/it]

Batch 150, Loss: 0.1765, Accuracy: 95.60%


Training:  38%|███▊      | 200/531 [10:47<17:50,  3.24s/it]

Batch 200, Loss: 0.0308, Accuracy: 95.48%


Training:  47%|████▋     | 250/531 [13:28<15:09,  3.24s/it]

Batch 250, Loss: 0.1020, Accuracy: 95.51%


Training:  56%|█████▋    | 300/531 [16:09<12:26,  3.23s/it]

Batch 300, Loss: 0.0572, Accuracy: 95.61%


Training:  66%|██████▌   | 350/531 [18:50<09:40,  3.21s/it]

Batch 350, Loss: 0.1468, Accuracy: 95.72%


Training:  75%|███████▌  | 400/531 [21:32<07:01,  3.22s/it]

Batch 400, Loss: 0.1820, Accuracy: 95.78%


Training:  85%|████████▍ | 450/531 [24:13<04:20,  3.21s/it]

Batch 450, Loss: 0.1296, Accuracy: 95.83%


Training:  94%|█████████▍| 500/531 [26:54<01:39,  3.21s/it]

Batch 500, Loss: 0.1545, Accuracy: 95.86%


Training: 100%|██████████| 531/531 [28:30<00:00,  3.22s/it]


Processed 531 batches
Training Loss: 0.1238, Accuracy: 95.78%
Training Loss: 0.1238, Training Accuracy: 95.78%


Evaluating: 100%|██████████| 263/263 [05:14<00:00,  1.20s/it]


Accuracy: 89.34%
Precision: 0.5941
Recall: 0.8657
F1-Score: 0.7046
Confusion Matrix:
[[6446  731]
 [ 166 1070]]
Validation Accuracy: 89.34%, F1-Score: 0.7046

Epoch 8/10
----------


Training:   9%|▉         | 50/531 [02:41<25:40,  3.20s/it]

Batch 50, Loss: 0.1021, Accuracy: 96.38%


Training:  19%|█▉        | 100/531 [05:22<23:08,  3.22s/it]

Batch 100, Loss: 0.1184, Accuracy: 96.03%


Training:  28%|██▊       | 150/531 [08:04<20:26,  3.22s/it]

Batch 150, Loss: 0.0694, Accuracy: 95.85%


Training:  38%|███▊      | 200/531 [10:46<17:44,  3.22s/it]

Batch 200, Loss: 0.0262, Accuracy: 95.89%


Training:  47%|████▋     | 250/531 [13:27<15:03,  3.22s/it]

Batch 250, Loss: 0.1234, Accuracy: 95.84%


Training:  56%|█████▋    | 300/531 [16:11<12:27,  3.24s/it]

Batch 300, Loss: 0.0600, Accuracy: 95.82%


Training:  66%|██████▌   | 350/531 [18:52<09:45,  3.23s/it]

Batch 350, Loss: 0.0294, Accuracy: 95.82%


Training:  75%|███████▌  | 400/531 [21:36<07:02,  3.23s/it]

Batch 400, Loss: 0.1299, Accuracy: 95.77%


Training:  85%|████████▍ | 450/531 [24:19<04:22,  3.24s/it]

Batch 450, Loss: 0.1536, Accuracy: 95.90%


Training:  94%|█████████▍| 500/531 [27:04<01:44,  3.38s/it]

Batch 500, Loss: 0.0903, Accuracy: 96.01%


Training: 100%|██████████| 531/531 [28:42<00:00,  3.24s/it]


Processed 531 batches
Training Loss: 0.1179, Accuracy: 95.95%
Training Loss: 0.1179, Training Accuracy: 95.95%


Evaluating: 100%|██████████| 263/263 [05:13<00:00,  1.19s/it]


Accuracy: 89.04%
Precision: 0.5857
Recall: 0.8681
F1-Score: 0.6995
Confusion Matrix:
[[6418  759]
 [ 163 1073]]
Validation Accuracy: 89.04%, F1-Score: 0.6995

Epoch 9/10
----------


Training:   9%|▉         | 50/531 [02:45<26:59,  3.37s/it]

Batch 50, Loss: 0.0879, Accuracy: 95.69%


Training:  19%|█▉        | 100/531 [05:31<23:14,  3.24s/it]

Batch 100, Loss: 0.1965, Accuracy: 95.72%


Training:  28%|██▊       | 150/531 [08:19<21:13,  3.34s/it]

Batch 150, Loss: 0.3719, Accuracy: 95.94%


Training:  38%|███▊      | 200/531 [11:09<17:43,  3.21s/it]

Batch 200, Loss: 0.2968, Accuracy: 95.92%


Training:  47%|████▋     | 250/531 [13:58<15:43,  3.36s/it]

Batch 250, Loss: 0.0856, Accuracy: 96.08%


Training:  56%|█████▋    | 300/531 [16:39<12:19,  3.20s/it]

Batch 300, Loss: 0.0237, Accuracy: 96.06%


Training:  66%|██████▌   | 350/531 [19:20<09:43,  3.22s/it]

Batch 350, Loss: 0.1392, Accuracy: 96.03%


Training:  75%|███████▌  | 400/531 [22:14<07:12,  3.30s/it]

Batch 400, Loss: 0.0715, Accuracy: 96.09%


Training:  85%|████████▍ | 450/531 [25:21<05:45,  4.27s/it]

Batch 450, Loss: 0.2055, Accuracy: 96.04%


Training:  94%|█████████▍| 500/531 [28:06<01:39,  3.20s/it]

Batch 500, Loss: 0.1421, Accuracy: 96.09%


Training: 100%|██████████| 531/531 [29:53<00:00,  3.38s/it]


Processed 531 batches
Training Loss: 0.1142, Accuracy: 96.12%
Training Loss: 0.1142, Training Accuracy: 96.12%


Evaluating: 100%|██████████| 263/263 [05:26<00:00,  1.24s/it]


Accuracy: 88.85%
Precision: 0.5805
Recall: 0.8697
F1-Score: 0.6962
Confusion Matrix:
[[6400  777]
 [ 161 1075]]
Validation Accuracy: 88.85%, F1-Score: 0.6962

Epoch 10/10
----------


Training:   9%|▉         | 50/531 [02:44<26:52,  3.35s/it]

Batch 50, Loss: 0.1025, Accuracy: 95.88%


Training:  19%|█▉        | 100/531 [05:25<23:54,  3.33s/it]

Batch 100, Loss: 0.0862, Accuracy: 96.44%


Training:  28%|██▊       | 150/531 [08:11<21:07,  3.33s/it]

Batch 150, Loss: 0.0681, Accuracy: 96.58%


Training:  38%|███▊      | 200/531 [11:00<18:04,  3.28s/it]

Batch 200, Loss: 0.1324, Accuracy: 96.67%


Training:  47%|████▋     | 250/531 [13:43<15:03,  3.22s/it]

Batch 250, Loss: 0.2490, Accuracy: 96.39%


Training:  56%|█████▋    | 300/531 [16:27<12:24,  3.22s/it]

Batch 300, Loss: 0.0142, Accuracy: 96.31%


Training:  66%|██████▌   | 350/531 [19:14<09:45,  3.24s/it]

Batch 350, Loss: 0.1461, Accuracy: 96.22%


Training:  75%|███████▌  | 400/531 [22:00<07:03,  3.23s/it]

Batch 400, Loss: 0.0755, Accuracy: 96.20%


Training:  85%|████████▍ | 450/531 [24:41<04:19,  3.20s/it]

Batch 450, Loss: 0.3194, Accuracy: 96.20%


Training:  94%|█████████▍| 500/531 [27:23<01:39,  3.21s/it]

Batch 500, Loss: 0.2029, Accuracy: 96.27%


Training: 100%|██████████| 531/531 [29:00<00:00,  3.28s/it]


Processed 531 batches
Training Loss: 0.1126, Accuracy: 96.29%
Training Loss: 0.1126, Training Accuracy: 96.29%


Evaluating: 100%|██████████| 263/263 [05:18<00:00,  1.21s/it]

Accuracy: 88.07%
Precision: 0.5601
Recall: 0.8746
F1-Score: 0.6829
Confusion Matrix:
[[6328  849]
 [ 155 1081]]
Validation Accuracy: 88.07%, F1-Score: 0.6829

Training completed in 351.28 minutes
Best validation accuracy: 93.91%
----------------------------------------------------------------------------


Evaluate Model using Test Set

In [11]:
# Load the model
print("Evaluating on test set...")

# Use the updated weights parameter instead of deprecated 'pretrained'
weights = MobileNet_V3_Large_Weights.DEFAULT
model = mobilenet_v3_large(weights=weights)
model.classifier[3] = nn.Linear(model.classifier[3].in_features, 2)  # 2 classes: cracked / not cracked

# Load trained weights
model.load_state_dict(torch.load('../model/Optimize_MobileNetV3_concrete_crack_detector.pth'))
model.eval()

# Define the transform for test data
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Evaluation function
def evaluate_model_on_split(split_name):
    base_path = f"../artifact_folder/{split_name}"
    labels_df = pd.read_csv(os.path.join(base_path, "labels.csv"))
    images_dir = os.path.join(base_path, "images")

    y_true, y_pred, y_score = [], [], []

    for _, row in labels_df.iterrows():
        img_path = os.path.join(images_dir, row["filename"])
        image = Image.open(img_path).convert("RGB")
        input_tensor = transform(image).unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(input_tensor)
            pred = output.argmax(dim=1).item()
            prob = torch.softmax(output, dim=1)[0][1].item()

        label = 1 if row["label"].lower() == "cracked" else 0
        y_true.append(label)
        y_pred.append(pred)
        y_score.append(prob)

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1-Score": f1_score(y_true, y_pred, zero_division=0),
        "AUC-ROC": roc_auc_score(y_true, y_score),
        "Confusion Matrix": confusion_matrix(y_true, y_pred).tolist()
    }

# Run on all sets
for split in ['train', 'val', 'test']:
    print(f"📊 Evaluation for {split.upper()}")
    metrics = evaluate_model_on_split(split)
    for k, v in metrics.items():
        print(f"{k}: {v}")
    print()
print(f"----------------------------------------------------------------------------")
print("Training and evaluation completed!")

Evaluating on test set...
📊 Evaluation for TRAIN
Accuracy: 0.9712989156058462
Precision: 0.9859035119698627
Recall: 0.9562706270627063
F1-Score: 0.9708610064022019
AUC-ROC: 0.9934172272804165
Confusion Matrix: [[8368, 116], [371, 8113]]

📊 Evaluation for VAL
Accuracy: 0.8806608819683822
Precision: 0.5601036269430052
Recall: 0.8745954692556634
F1-Score: 0.6828806064434618
AUC-ROC: 0.9540645391404492
Confusion Matrix: [[6328, 849], [155, 1081]]

📊 Evaluation for TEST
Accuracy: 0.8771241830065359
Precision: 0.5652392947103274
Recall: 0.8677494199535963
F1-Score: 0.6845637583892618
AUC-ROC: 0.9481623230785171
Confusion Matrix: [[6259, 863], [171, 1122]]

----------------------------------------------------------------------------
Training and evaluation completed!
